Inline git dirty check
We're moving towards https://issues.redhat.com/browse/ROX-27488 and
so there's no need to call the external script if the check can be
made locally.

Note that compared to
https://github.com/stackrox/stackrox/blob/b170ccb6e8193151ed5d14799ae984c8c1402724/.konflux/scripts/fail-build-if-git-is-dirty.sh
this script doesn't try to restore Dockerfiles because it is executed
before prefetch task which makes those changes.

diff --git a/tasks/determine-image-tag-task.yaml b/tasks/determine-image-tag-task.yaml
--- a/tasks/determine-image-tag-task.yaml
+++ b/tasks/determine-image-tag-task.yaml
@@ -54,7 +54,21 @@ spec:
 
       dnf -y install git make
 
-      .konflux/scripts/fail-build-if-git-is-dirty.sh
+      function fail_build_if_git_is_dirty() {
+        echo "Checking that there are no uncommitted changes in the git repo."
+        echo "If this command fails, you should see the list of modified files below."
+        echo "You need to find the reason and prevent it because otherwise the 'make tag' output will include '-dirty' which likely isn't what you want."
+        echo ""
+
+        if git status --porcelain | grep '.' >&2 ; then
+          >&2 echo "ERROR: Modified files found."
+          exit 2
+        else
+          echo "git repo looks clean."
+        fi
+      }
+
+      fail_build_if_git_is_dirty
 
       source_branch="$(params.SOURCE_BRANCH)"
 
