spike: wait for image for specific commit

diff --git a/tasks/wait-for-image-task.yaml b/tasks/wait-for-image-task.yaml
--- a/tasks/wait-for-image-task.yaml
+++ b/tasks/wait-for-image-task.yaml
@@ -8,6 +8,10 @@ spec:
   - name: IMAGE
     description: Image reference.
     type: string
+  - name: DESIRED_GIT_REF
+    valueFrom:
+      fieldRef:
+        fieldPath: metadata.labels['pipelinesascode.tekton.dev/sha']
   results:
   - name: IMAGE_DIGEST
     description: Image digest in the format `sha256:abcdef0123`.
@@ -27,27 +31,30 @@ spec:
 
       echo "Waiting for image $(params.IMAGE) to become available..."
       while true; do
-        if skopeo inspect --raw "docker://$(params.IMAGE)"; then
-          break
+        raw_info="$(skopeo inspect \
+          --retry-times 10 \
+          --format '{{.Digest}} {{ index .Labels "vcs-ref" }} {{ index .Labels "source-location" }}' \
+          --no-tags \
+          "docker://$(params.IMAGE)")"
+
+        # Turning raw_info into an array for easier handling.
+        infos=( $raw_info )
+        if [[ "${#infos[@]}" -ne 3 ]]; then
+          >&2 echo "ERROR: Not all required information was found. Verify that the 'vcs-ref' and 'source-location' labels are set on the image $(params.IMAGE)."
+          exit 1
         fi
-        sleep 1m
+
+        if [[ "${infos[1]}" == "$(params.DESIRED_GIT_REF)" ]]; then
+          break
+        else
+          >&2 echo "ERROR: The Git reference of the image $(params.IMAGE) does not match the desired Git reference $(params.DESIRED_GIT_REF)."
+          # Continue waiting
+          sleep 1m
+        fi
       done
 
       echo "Image $(params.IMAGE) found."
-
-      raw_info="$(skopeo inspect \
-        --retry-times 10 \
-        --format '{{.Digest}} {{ index .Labels "vcs-ref" }} {{ index .Labels "source-location" }}' \
-        --no-tags \
-        "docker://$(params.IMAGE)")"
-
-      # Turning raw_info into an array for easier handling.
-      infos=( $raw_info )
-      if [[ "${#infos[@]}" -ne 3 ]]; then
-        >&2 echo "ERROR: Not all required information was found. Verify that the 'vcs-ref' and 'source-location' labels are set on the image $(params.IMAGE)."
-        exit 1
-      fi
-
+      
       # Output
       echo -n "${infos[0]}" | tee "$(results.IMAGE_DIGEST.path)"
       echo
