check that all tasks finish successfully

diff --git a/tasks/wait-for-image-task.yaml b/tasks/wait-for-image-task.yaml
--- a/tasks/wait-for-image-task.yaml
+++ b/tasks/wait-for-image-task.yaml
@@ -52,13 +52,28 @@ spec:
       echo -n "${infos[2]}" | tee "$(results.GIT_REPO.path)"
 
       IMAGE_DIGEST="${infos[0]}"
-      echo "Waiting for attestation for $(params.IMAGE)@${IMAGE_DIGEST} to appear..."
+      echo "Waiting for attestation for ${IMAGE}@${IMAGE_DIGEST} to appear..."
       while true; do
-        if cosign tree "$(params.IMAGE)@${IMAGE_DIGEST}" | grep -qE "quay.io/.*:sha256-.*\.att$"; then
+        if cosign tree "${IMAGE}@${IMAGE_DIGEST}" | grep -qE "quay.io/.*:sha256-.*\.att$"; then
           break
         fi
-        echo "Attestation for $(params.IMAGE)@${IMAGE_DIGEST} not (yet) found, sleeping and retrying..."
+        echo "Attestation for ${IMAGE}@${IMAGE_DIGEST} not (yet) found, sleeping and retrying..."
         sleep 1m
       done
 
-      echo "Attestion for $(params.IMAGE)@${IMAGE_DIGEST} found, which means PipelineRun finished successfully and the image can be used further."
+      echo "Attestion for ${IMAGE}@${IMAGE_DIGEST} found, which means PipelineRun finished. Checking if any tasks finished unsuccessfully."
+
+      no_success=$(cosign download attestation "${IMAGE}@${IMAGE_DIGEST}" | \
+        jq -r '.payload' | \
+        base64 -d | \
+        jq '.predicate.buildConfig.tasks | [ .[] | select(.status != "Succeeded") ] | length'
+      )
+
+      if [ "${no_success}" -gt 0 ]; then
+        echo "ERR: At least one task has failed during build of ${IMAGE}@${IMAGE_DIGEST}."
+        echo "ERR: Try building it again and re-run this pipeline."
+        exit 1
+      else
+        echo "The pipeline that built ${IMAGE}@${IMAGE_DIGEST} finished successfully."
+        echo "Accepting this image."
+      fi
