auto-sense if the git check is required

diff --git a/tasks/wait-for-image-task.yaml b/tasks/wait-for-image-task.yaml
--- a/tasks/wait-for-image-task.yaml
+++ b/tasks/wait-for-image-task.yaml
@@ -8,10 +8,6 @@ spec:
   - name: IMAGE
     description: Image reference.
     type: string
-  - name: ENABLE_GIT_REF_CHECK
-    description: Whether to check if the image was built for the same commit as the one specified in the `DESIRED_GIT_REF` parameter.
-    type: string
-    default: "true"
   results:
   - name: IMAGE_DIGEST
     description: Image digest in the format `sha256:abcdef0123`.
@@ -29,6 +25,10 @@ spec:
       valueFrom:
         fieldRef:
           fieldPath: metadata.labels['pipelinesascode.tekton.dev/sha']
+    - name: REPOSITORY_URL
+      valueFrom:
+        fieldRef:
+          fieldPath: metadata.annotations['pipelinesascode.tekton.dev/repo-url']
     script: |
       #!/usr/bin/env bash
 
@@ -54,17 +54,22 @@ spec:
           exit 1
         fi
 
-        if [[ "$(params.ENABLE_GIT_REF_CHECK)" == "true" ]]; then
-          if [[ "${infos[1]}" == "${DESIRED_GIT_REF}" ]]; then
-            >&2 echo "INFO: Git reference check is enabled and the found image $(params.IMAGE)@${infos[0]} is built for the expected commit (${DESIRED_GIT_REF})."
+        digest="${infos[0]}"
+        git_ref="${infos[1]}"
+        source_repository="${infos[2]}"
+
+        if [[ "${source_repository}" == "${REPOSITORY_URL}" ]]; then
+          >&2 echo "INFO: Checking the Git reference is required because this image is built from the same repository as the current pipeline."
+          if [[ "${git_ref}" == "${DESIRED_GIT_REF}" ]]; then
+            >&2 echo "INFO: The found image $(params.IMAGE)@${digest} is built for the expected commit (${DESIRED_GIT_REF}). Accepting this image."
             break
           else
-            >&2 echo "WARNING: The found image $(params.IMAGE)@${infos[0]} seems to be built for a different commit (${infos[1]}) than the one expected (${DESIRED_GIT_REF}). This could happen for a tagged build when a git tag was moved and newly-triggered pipelines haven't finished yet. This task will keep waiting for the image with the matching tag to appear."
+            >&2 echo "WARNING: The found image $(params.IMAGE)@${digest} seems to be built for a different commit (${git_ref}) than the one expected (${DESIRED_GIT_REF}). This could happen for a tagged build when a git tag was moved and newly-triggered pipelines haven't finished yet. This task will keep waiting for the image with the matching tag to appear."
             # Continue waiting
             sleep 1m
           fi
         else
-          >&2 echo "INFO: Git reference check is disabled. Accepting this image."
+          >&2 echo "INFO: Checking the Git reference is not required because this image is built from a different repository than the current pipeline. Accepting this image."
           break
         fi
       done
@@ -72,14 +77,14 @@ spec:
       echo "Image $(params.IMAGE) found."
 
       # Output
-      echo -n "${infos[0]}" | tee "$(results.IMAGE_DIGEST.path)"
+      echo -n "${digest}" | tee "$(results.IMAGE_DIGEST.path)"
       echo
-      echo -n "${infos[1]}" | tee "$(results.GIT_REF.path)"
+      echo -n "${git_ref}" | tee "$(results.GIT_REF.path)"
       echo
-      echo -n "${infos[2]}" | tee "$(results.GIT_REPO.path)"
+      echo -n "${source_repository}" | tee "$(results.GIT_REPO.path)"
       echo
 
-      IMAGE_WITH_DIGEST="$(params.IMAGE)@${infos[0]}"
+      IMAGE_WITH_DIGEST="$(params.IMAGE)@${digest}"
       echo "Waiting for attestation for ${IMAGE_WITH_DIGEST} to appear..."
       while true; do
         if cosign tree "${IMAGE_WITH_DIGEST}" | grep -qE "quay.io/.*:sha256-.*\.att$"; then
